name: mvn_jepsen_test

on:
  push:
    branches: [ lihang/jepsen-test ]
  pull_request:
    branches: [ lihang/jepsen-test ]





jobs:
  mvn_jepsen_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: ls -lh ~/.ssh

      - name: Package
        run: mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V

      - name: start docker klein-jepsen-server container
        run: ls -lh && docker-compose -f klein-jepsen/klein-jepsen-server/cluster.yaml up -d

      - name: test
        run: sleep 5 && docker ps && ssh -oPort=10001 root@127.0.0.1 'ls -lh'